### ISSUE TITLE
1_153_145

### ISSUE THREAD

**Issue by phamvannhatvu** [QuyLe-Minh/DSATestcase_Assignment2#1]
Lệnh printMH bị sai, có thể do khi remove phần tử trong minHeap ông chưa reheapUp. Vì khi tui xóa hàm reheapUp trong hàm remove của minHeap thi kết quả ra giống với ông.

**Comment by QuyLe-Minh** [comment]
Hi,

Mình ghi nhận lỗi sai nha. Mình gửi lại bạn file expected1 mới, bạn check lại xem đúng không rồi mình public nhé.

11-2
11-25738-5
5-18724-1
15-28398-1
5-1
12-1
11-5
15-1
26-2
26-4633-2
12-22283-1
11-25738-8
5-18724-2
15-28398-4
11-25738-9
5-18724-2
15-28398-4
26-4633-4
12-22283-2
13-30795-6
11-25738-9
14-10922-1
15-28398-4
23-22-1
5-18724-2
16-28398-1
1-0-2
7-17734-1
16-1
14-1
23-1
11-9
12-2
4-2
15-4
1-2
7-1
5-2
13-7
26-4
2-5537-1
2-5537-1
15-1
5-1
16-1
1-2
12-1
13-1
24-2
14-2
2-1
11-2
23-2
2-5537-1
26-4633-1
13-22283-1
14-30795-2
15-1
5-1
16-1
1-2
17-2
13-1
26-1
14-2
2-1
11-2
24-3
12-2
7-1
23-2
28-1
24-14134-3
23-22-2
11-25738-3
1-0-2
12-10922-2
5-18724-1
15-28398-2
19-9362-1
7-17734-1
17-25546-2
16-28398-1
5-1
16-1
28-1
13-2
8-2
26-2
12-2
17-3
9-2
27-1
29-1
14-5
24-4
2-1
18-2
30-1
7-1
31-1
32-1
4-2
23-2
15-5
11-3
32-24029-1
2-5537-1
4-20291-2
8-24551-2
9-16615-2
26-4633-2
27-1561-1
13-22283-2
14-30795-5
28-15291-1
30-24029-1
31-6553-1
32-24029-2
2-5537-1
12-11-2
4-20291-3
24-16983-1
10-679-1
8-24551-3
9-16615-2
26-4633-2
27-1561-1
13-22283-2
14-30795-5
28-15291-1
29-14043-1
31-6553-1
6-18724-2
7-17734-1
15-28398-1
23-22-1
5-18724-1
11-25738-1
17-29808-1
28-1
27-1
7-1
5-1
9-2
13-2
15-1
14-5
6-2
2-1
24-1
8-3
10-1
17-1
32-2
31-1
29-1
4-3
12-2
11-1
26-2
23-1

**Comment by phamvannhatvu** [comment]
Mình check thấy đúng rồi bạn!
